### ISSUE TITLE
Slow start-up

### ISSUE THREAD

**Issue by iNko97** [trainphreak/SketchMap#18]
The plugin is awesome, but it takes a very long time to load all maps when reloading the server, about 3 minutes per 5:3 map...
Am I doing something incorrectly or is it a known issue?

**Comment by trainphreak** [comment]
I mean, it loads kinda slow no matter what because everything is stored in special files that have to be read into memory on startup, but that's ridiculous. What was the exact command you ran to create that sketchmap?

**Comment by iNko97** [comment]
/sketchmap create name link 5:3
then I pasted each one of them once with /sketchmap place name

**Comment by trainphreak** [comment]
Well, that's the right syntax but I can't tell what that will actually do
without the exact command you ran.

Also, if you place the same map in the world multiple times, it runs off
the same internal data, so the number of sketchmap files is what counts,
not the number of times they're in the world (high map count will cause
your client to lag due to the render load; put a few thousand maps in item
frames in a small area and you'll see what I mean :P )

**Comment by iNko97** [comment]
This is the exact command I ran, is png size a factor? (106kb)
/sketchmap create gruppi https://i.imgur.com/WTLS2qM.png 5:3

The client lag is not a factor, my maps are very spaced out between each other, so there are max 60 per place, the problem here is just the load time.
I have about 20 5:3 files, and each takes 3 minutes, ramping up server start up to an hour...

**Comment by trainphreak** [comment]
PNG size is indeed a factor, as the sketchmap creation process downloads the image and saves it to a file in base64 encoding, but 106KB isn't all that large (I think). Could you find the file in plugins/SketchMap/sketchmaps/gruppi and upload it here so I can take a look at what it's trying to load?

**Comment by iNko97** [comment]
[descrizionenl.sketchmap.txt](https://github.com/trainphreak/SketchMap/files/1354758/descrizionenl.sketchmap.txt)

**Comment by iNko97** [comment]
[descrizionenl.sketchmap.txt](https://github.com/trainphreak/SketchMap/files/1354760/descrizionenl.sketchmap.txt)

I will try to compress the image to a multiple of 128 and redo the command, see if that fastens the load process. Maybe it does, it reduced last startup time of a single map to 1min per 5:3 map.

I noticed that during startup 2 of my cpu cores go up to 100%.

**Comment by trainphreak** [comment]
Well, I just took another look at the code and I'd highly recommend compressing your images to the size you want them to be (Ex: a 5:3 sketchmap should be a 640x384 image) before running '/sketchmap create', because it actually downloads the fullsize image, and stores and loads and resizes that fullsize image to the specified dimensions when the server starts.

That said, a full minute seems a bit long to load and resize an image that's 658x444. Did it take that long to load and resize it when you first created it? (the server would have lost client connections if it had taken more than a couple seconds, though if left alone, it would have completed and resumed normally)

**Comment by iNko97** [comment]
The time it took to load and resize when first creating any of them was about 4 seconds, it's loading them all that fills up the cpu and goes slow. I will compress all of them, and share the results.

**Comment by trainphreak** [comment]
See, that's what is so confusing about this. If it was able to download the entire picture and resize it in a few seconds, why does it take a minute or more to load from disk? Is your hardware doing a lot of other disk-intensive operations at the same time, or is your hard drive super-old or something? (or maybe even failing? idk)

**Comment by mibby** [comment]
> everything is stored in special files that have to be read into memory on startup

Still would be nice to have some form of multi-threaded loading or loading the sketchmaps post start-up to avoid long server restarts with dozens of maps. :)

```
[03:13:20] [Server thread/INFO]: [SketchMap] Enabling SketchMap v1.4.2
[03:13:21] [Server thread/INFO]: [SketchMap] 10/32 sketchmaps loaded.
[03:13:22] [Server thread/INFO]: [SketchMap] 20/32 sketchmaps loaded.
[03:13:24] [Server thread/INFO]: [SketchMap] 30/32 sketchmaps loaded.
[03:13:24] [Server thread/INFO]: [SketchMap] Finished! 32 sketchmaps loaded
```

**Comment by trainphreak** [comment]
Yeah, working on that. Code is easy, good code is hard, and good docs are really hard.

**Comment by trainphreak** [comment]
Yeah, so I'm pretty much done working on Sketchmap. I wrote a similar plugin called Picmap (https://www.spigotmc.org/resources/picmap.50826/) that stores the image data directly in the maps instead of replacing the renderer like Sketchmap does, so it doesn't have the startup issues and uses way fewer resources as well. It also does the image download and processing in a separate thread instead of on the server's main thread, and I'm in the process of testing an integrated Sketchmap-->Picmap conversion command (currently there's an external utility you can run).
